---
- name: PROVISION A DEVICE
  hosts: neteng_lab
  connection: local
  gather_facts: no

  roles:
    - Juniper.junos

  tasks:

    # uses the junos_config module provided by Juniper (ansible-galaxy) 
    - name : LOAD BASE CONFIG (JUNOS)
      junos_config:
        src : "../BaseConfig/juniper/JunosBaseConfig.set"
        comment : "Base config pushed by ansible"
      tags:
        - push_baseconfig_junos
      when: ansible_network_os == 'junos'

    # uses the default ansible core module for Arista eos_config
    - name : LOAD BASE CONFIG (ARISTA)
      eos_config:
        src : "../BaseConfig/juniper/AristaBaseConfig.cfg"
        comment : "Base config pushed by ansible"
      tags:
        - push_baseconfig_eos
      when: ansible_network_os == 'eos'

    # Uses the REST API endpoints exposed by LibreNMS.  
    - name : ADD DEVICE to LIBRENMS MONITORING
      command : "../librenms_rest/ManageDevices.py add {{ inventory_hostname }}"
      become: yes
      become_user: root
      tags :
        - librenms

    # Uses the REST API endpoints exposed by NetDot.
    - name : ADD DEVICE to NETDOT DB
      command : "../netdot_add_remove_dev/netdot_ManageDevice.py add {{ inventory_hostname }}"
      become: yes
      become_user: root
      tags :
        - netdot

    # Uses the module exposed by ansible-galaxy from Juniper 
    - name : PUSH CODE & INITIATE UPGRADE (if device == juniper)
      juniper_junos_software:
        local_package : "../nos/junos/jinstall-host-qfx-5-16.1R4.7-signed.tgz"
        validate : yes
      register: response
      when: ansible_network_os == 'junos'
    - debug:
        var: response

    # Uses the core ansible eos_command module
    - name: PUSH CODE and UPGRADE (if device == arista)
      eos_command:
        commands:
          - 'install source {{ swi_path }} now'
      when: ansible_network_os == 'eos'
    - debug:
        var: response
